### ISSUE TITLE
Stesura del documento dei requisiti

### ISSUE THREAD

**Issue by espositoandrea** [F-S-C/Emotionally#4]
Dopo aver completato la definizione dei requisiti, è necessario stendere il documento dei requisiti.

Questo lavoro è affidato a @ReginaZaccaria, che lavorerà sulla branch `documento-requisiti`.

**Comment by espositoandrea** [comment]
Come richiesto da @ReginaZaccaria, ho migliorato il layout del diagramma dei casi d'uso.

**Comment by ReginaZaccaria** [comment]
La stesura della documentazione dei requisiti è terminata. Sono state introdotte le sezioni riguardanti le "Generalità",  "Requisiti del sito" e "Requisiti di gestione progetto".  
Inoltre sono state realizzate le gabbie logiche di massima da @Davidedes, il modello concettuale della base di dati da @Ax3lFernus e sono stati creati i diagrammi dei casi d'uso e le tabelle degli stessi.
Tutto il layout grafico delle tabelle, diagrammi e gabbie logiche sono state migliorate da @espositoandrea.
Per quanto riguarda i contenuti sono stati redatti in comune accordo con tutto il team.

Per questo motivo, in quanto conclusa, è stata creata la PR #12
