### ISSUE TITLE
Stesura del documento del piano di qualità

### ISSUE THREAD

**Issue by espositoandrea** [F-S-C/Emotionally#5]
È necessario stendere il documento del piano di qualità.

**Comment by Ax3lFernus** [comment]
Effettuata la stesura del documento del piano di qualità. All'interno è stato riportato il diagramma di gantt, la descrizione della divisione dei compiti di ogni componente del team e l'analisi dei rischi tramite una privacy policy consultabile [online](https://f-s-c.github.io/emotionally_policy/privacy_policy.html).

Dopo una ulteriore verifica effettuata da @Ax3lFernus  e @prewarning procediamo alla chiusura della seguente issues creando la PR #13.
