### ISSUE TITLE
Creazione del prototipo di navigazione

### ISSUE THREAD

**Issue by espositoandrea** [F-S-C/Emotionally#6]
È necessario definire un prototipo di navigazione. Tale lavoro è assegnato a @Davidedes (che fornirà un file `.xd`).

**Comment by Davidedes** [comment]
Il prototipo di navigazione è completato, aspetto l'approvazione del revisore per dichiarare la issue finita.

**Comment by Ax3lFernus** [comment]
Prototipo revisionato ed approvato. 
È stata creata la PR #14 per effettuare il merge delle modifiche nella branch master.

Si procede alla chiusura della issue in quanto completata.
